stage-2-uname

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -33,19 +33,33 @@ pipeline {
             sh '''
                 if ! command -v terraform &> /dev/null; then
                     echo "Terraform not found, installing..."
-                    
-                    if [ -f /etc/debian_version ]; then
-                        echo "Detected Debian-based system"
-                        sudo apt-get update -y
-                        sudo apt-get install -y unzip wget
-                    elif [ -f /etc/redhat-release ]; then
-                        echo "Detected RHEL-based system"
-                        sudo yum install -y unzip wget
-                    elif [ -f /etc/alpine-release ]; then
-                        echo "Detected Alpine Linux"
-                        sudo apk add --no-cache unzip wget
+
+                    OS_TYPE=$(uname -s)
+                    if [ "$OS_TYPE" = "Linux" ]; then
+                        if [ -f /etc/os-release ]; then
+                            . /etc/os-release
+                            case "$ID" in
+                                ubuntu|debian)
+                                    sudo apt-get update -y
+                                    sudo apt-get install -y unzip wget
+                                    ;;
+                                centos|rhel|fedora|amzn)
+                                    sudo yum install -y unzip wget
+                                    ;;
+                                alpine)
+                                    sudo apk add --no-cache unzip wget
+                                    ;;
+                                *)
+                                    echo "Unsupported Linux distribution: $ID"
+                                    exit 1
+                                    ;;
+                            esac
+                        else
+                            echo "Cannot determine OS type."
+                            exit 1
+                        fi
                     else
-                        echo "Unsupported OS"
+                        echo "Unsupported OS: $OS_TYPE"
                         exit 1
                     fi
 
@@ -59,6 +73,7 @@ pipeline {
         }
     }
 }
+
 
 
         // Stage 3: Install TFLint
